name: Joybox
permalink: /:categories/:title/
baseurl: ''
pygments: true
markdown: redcarpet
paginate: 3
paginate_path: "/version-history/:num"
redcarpet:
  extensions: ["hard_wrap",
               "no_intra_emphasis",
               "tables",
               "fenced_code_blocks",
               "autolink",
               "strikethrough",
               "lax_spacing",
               "space_after_headers",
               "with_toc_data",
               "xhtml"]